export const API_BASE_URL = "https://admin-api.fact-flow.in/api/v1";
// export const API_BASE_URL = "https://keshav.bugslayer.in/api/v1";

export const statesIecSubscriptions = [
  "RA VADODARA",
  "RA JAIPUR",
  "RA KOCHI",
  "RA DELHI",
  "RA KANDLA FT",
  "RA SURAT",
  "RA KOLKATA",
  "RA AHMEDABAD",
  "RA PANIPAT",
  "RA HYDERABAD",
  "RA RAJKOT",
  "RA MUMBAI",
  "RA PUNE",
  "RA NAGPUR",
  "RA COIMBATORE",
  "RA BENGALURU",
  "RA INDORE",
  "RA VISAKHAPATNAM",
  "RA GUWAHATI",
  "RA LUDHIANA",
  "RA CHENNAI",
  "RA KANPUR",
  "RA VARANASI",
  "RA VIZAG EPZ",
  "RA SRINAGAR",
];

export const statesAndCityGstSubscriptions = {
  state: [
    "Jammu & Kashmir",
    "Himachal Pradesh",
    "Punjab",
    "Chandigarh",
    "Uttarakhand",
    "Haryana",
    "Delhi",
    "Rajasthan",
    "Uttar Pradesh",
    "Bihar",
    "Sikkim",
    "Arunachal Pradesh",
    "Nagaland",
    "Manipur",
    "Mizoram",
    "Tripura",
    "Meghalaya",
    "Assam",
    "West Bengal",
    "Jharkhand",
    "Odisha",
    "Chhattisgarh",
    "Madhya Pradesh",
    "Gujarat",
    "Daman and Diu",
    "Dadra and Nagar Haveli",
    "Maharashtra",
    "Andhra Pradesh (Before split)",
    "Karnataka",
    "Goa",
    "Lakshadweep",
    "Kerala",
    "Tamil Nadu",
    "Puducherry",
    "Andaman and Nicobar Islands",
    "Telangana",
    "Andhra Pradesh (New)",
    "Other Territory",
    "Centre Jurisdiction",
  ],
  city: [
    "Jammu",
    "Budgam",
    "Samba",
    "Pulwama",
    "Ganderbal",
    "Srinagar",
    "Ramban",
    "Bandipore",
    "Baramulla",
    "Shopian",
    "Kupwara",
    "Anantnag",
    "Reasi",
    "Udhampur",
    "Kishtwar",
    "Kulgam",
    "Rajouri",
    "Poonch",
    "Kathua",
    "Shimla",
    "Kangra",
    "Kullu",
    "Una",
    "Solan",
    "Bilaspur",
    "Mandi",
    "Sirmaur",
    "Hamirpur",
    "Kinnaur",
    "Ludhiana",
    "Jalandhar",
    "Amritsar",
    "SAS Nagar",
    "Pathankot",
    "Fatehgarh Sahib",
    "Malerkotla",
    "Bathinda",
    "Sri Muktsar Sahib",
    "Sangrur",
    "Faridkot",
    "Kapurthala",
    "Patiala",
    "Hoshiarpur",
    "Mansa",
    "Rupnagar",
    "Fazilka",
    "Gurdaspur",
    "Ferozepur",
    "Barnala",
    "Shaheed Bhagat Singh Nagar",
    "Tarn Taran",
    "Moga",
    "Chandigarh",
    "Haridwar",
    "Nainital",
    "Dehradun",
    "Udham Singh Nagar",
    "Champawat",
    "Tehri Garhwal",
    "Almora",
    "Pithoragarh",
    "Uttarkashi",
    "Bageshwar",
    "Chamoli",
    "Pauri Garhwal",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Panchkula",
    "Palwal",
    "Sonipat",
    "Kurukshetra",
    "Fatehabad",
    "Karnal",
    "Kaithal",
    "Nuh",
    "Ambala",
    "Mahendragarh",
    "Yamunanagar",
    "Sirsa",
    "Jind",
    "Bhiwani",
    "Rohtak",
    "Panipat",
    "Charkhi Dadri",
    "Jhajjar",
    "Rewari",
    "Central Delhi",
    "South Delhi",
    "North West Delhi",
    "North East Delhi",
    "South West Delhi",
    "East Delhi",
    "New Delhi",
    "South East Delhi",
    "West Delhi",
    "North Delhi",
    "Shahdara",
    "Neem Ka Thana",
    "Bhilwara",
    "Jaipur",
    "Deeg",
    "Bikaner",
    "Jodhpur",
    "Kota",
    "Deedwana Kuchaman",
    "Alwar",
    "Khairthal Tijara",
    "Sikar",
    "Jaipur Rural",
    "Sirohi",
    "Kotputli Behror",
    "Rajsamand",
    "Ajmer",
    "Balotra",
    "Sri Ganganagar",
    "Dholpur",
    "Jhunjhunu",
    "Nagaur",
    "Beawar",
    "Chittorgarh",
    "Udaipur",
    "Sanchore",
    "Jaisalmer",
    "Phalodi",
    "Sawai Madhopur",
    "Tonk",
    "Pali",
    "Pratapgarh",
    "Hanumangarh",
    "Churu",
    "Banswara",
    "Karauli",
    "Jodhpur Rural",
    "Dungarpur",
    "Barmer",
    "Baran",
    "Jalore",
    "Shahpura",
    "Bundi",
    "Anupgarh",
    "Dudu",
    "Dausa",
    "Bharatpur",
    "Kekri",
    "Jhalawar",
    "Gangapur City",
    "Raebareli",
    "Gautambuddha Nagar",
    "Aligarh",
    "Lucknow",
    "Prayagraj",
    "Bulandshahr",
    "Hapur",
    "Kanpur Nagar",
    "Varanasi",
    "Gorakhpur",
    "Fatehpur",
    "Agra",
    "Ghaziabad",
    "Moradabad",
    "Mathura",
    "Basti",
    "Deoria",
    "Meerut",
    "Saharanpur",
    "Bareilly",
    "Rampur",
    "Siddharthnagar",
    "Ghazipur",
    "Kaushambi",
    "Gonda",
    "Muzaffarnagar",
    "Mau",
    "Kushinagar",
    "Amroha",
    "Chandauli",
    "Mirzapur",
    "Ayodhya",
    "Jhansi",
    "Bhadohi",
    "Bijnor",
    "Etawah",
    "Bagpat",
    "Kanpur Dehat",
    "Lakhimpur Kheri",
    "Firozabad",
    "Sambhal",
    "Jaunpur",
    "Shamli",
    "Sitapur",
    "Banda",
    "Kasganj",
    "Etah",
    "Maharajganj",
    "Ballia",
    "Azamgarh",
    "Budaun",
    "Balrampur",
    "Ambedkar Nagar",
    "Barabanki",
    "Lalitpur",
    "Mainpuri",
    "Shravasti",
    "Hardoi",
    "Sultanpur",
    "Farrukhabad",
    "Pilibhit",
    "Jalaun",
    "Auraiya",
    "Unnao",
    "Sonbhadra",
    "Shahjahanpur",
    "Hathras",
    "Bahraich",
    "Chitrakoot",
    "Amethi",
    "Sant Kabir Nagar",
    "Kannauj",
    "Mahoba",
    "Patna",
    "Samastipur",
    "Pashchim Champaran",
    "Vaishali",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    "Khagaria",
    "Begusarai",
    "Rohtas",
    "Purnea",
    "Kishanganj",
    "Nawada",
    "Siwan",
    "Aurangabad",
    "Katihar",
    "Purbi Champaran",
    "Gaya",
    "Jehanabad",
    "Jamui",
    "Sitamarhi",
    "Bhojpur",
    "Madhubani",
    "Buxar",
    "Nalanda",
    "Munger",
    "Araria",
    "Madhepura",
    "Lakhisarai",
    "Saran",
    "Gopalganj",
    "Sheohar",
    "Kaimur",
    "Supaul",
    "Sheikhpura",
    "Saharsa",
    "Banka",
    "Arwal",
    "Gangtok",
    "Gyalshing",
    "Namchi",
    "Changlang",
    "Papum Pare",
    "Keyi Panyor",
    "Lower Subansiri",
    "Itanagar Capital Complex",
    "Siang",
    "East Siang",
    "Lower Dibang Valley",
    "Lohit",
    "Zunheboto",
    "Dimapur",
    "Kohima",
    "Imphal West",
    "Thoubal",
    "Churachandpur",
    "Imphal East",
    "Aizawl",
    "Lawngtlai",
    "North Tripura",
    "Unakoti",
    "Sepahijala",
    "West Tripura",
    "Gomati",
    "East Khasi Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
    "West Garo Hills",
    "North Garo Hills",
    "East Garo Hills",
    "East Jaintia Hills",
    "Kamrup Metropolitan",
    "Kokrajhar",
    "Morigaon",
    "Nalbari",
    "Tinsukia",
    "Dibrugarh",
    "Bongaigaon",
    "Nagaon",
    "South Salmara Mankachar",
    "Golaghat",
    "Cachar",
    "Baksa",
    "Hailakandi",
    "Lakhimpur",
    "Karimganj",
    "Biswanath",
    "Dhemaji",
    "Kamrup",
    "Chirang",
    "Jorhat",
    "Barpeta",
    "Karbi Anglong",
    "West Karbi Anglong",
    "Dhubri",
    "Tamulpur",
    "Majuli",
    "Sivasagar",
    "Charaideo",
    "Goalpara",
    "Sonitpur",
    "Darrang",
    "Kolkata",
    "Purba Medinipur",
    "Malda",
    "Howrah",
    "North Twenty Four Parganas",
    "Darjeeling",
    "South Twenty Four Parganas",
    "Birbhum",
    "Paschim Bardhaman",
    "Bankura",
    "Murshidabad",
    "Hooghly",
    "Dakshin Dinajpur",
    "Paschim Medinipur",
    "Nadia",
    "Purba Bardhaman",
    "Uttar Dinajpur",
    "Alipurduar",
    "Cooch Behar",
    "Jalpaiguri",
    "Jhargram",
    "Purulia",
    "Kalimpong",
    "East Singhbhum",
    "Dhanbad",
    "Ranchi",
    "Hazaribag",
    "Lohardaga",
    "Bokaro",
    "Ramgarh",
    "Koderma",
    "Godda",
    "Dumka",
    "Pakur",
    "Chatra",
    "Palamu",
    "Deoghar",
    "Jamtara",
    "Sahibganj",
    "Giridih",
    "Garhwa",
    "Latehar",
    "West Singhbhum",
    "Seraikela Kharsawan",
    "Gumla",
    "Angul",
    "Khordha",
    "Ganjam",
    "Nabarangpur",
    "Koraput",
    "Puri",
    "Sambalpur",
    "Cuttack",
    "Baleswar",
    "Jajpur",
    "Bargarh",
    "Kalahandi",
    "Mayurbhanj",
    "Rayagada",
    "Nayagarh",
    "Kendujhar",
    "Jagatsinghpur",
    "Bhadrak",
    "Balangir",
    "Dhenkanal",
    "Boudh",
    "Kendrapara",
    "Malkangiri",
    "Deogarh",
    "Kandhamal",
    "Sundargarh",
    "Subarnapur",
    "Korba",
    "Raipur",
    "Durg",
    "Raigarh",
    "Bijapur",
    "Dantewada",
    "Rajnandgaon",
    "Balodabazar Bhatapara",
    "Janjgir Champa",
    "Mahasamund",
    "Sukma",
    "Bastar",
    "Sakti",
    "Surajpur",
    "Kabirdham",
    "Surguja",
    "Balod",
    "Manendragarh Chirmiri Bharatpur",
    "Korea",
    "Gariaband",
    "Kondagaon",
    "Balrampur Ramanujganj",
    "Sarangarh Bilaigarh",
    "Dhamtari",
    "Khairagarh Chhuikhadan Gandai",
    "Mohla Manpur Ambagarh Chouki",
    "Jashpur",
    "Bemetara",
    "Mungeli",
    "Indore",
    "Bhopal",
    "Singrauli",
    "Jabalpur",
    "Seoni",
    "Mandsaur",
    "Chhatarpur",
    "Pandhurna",
    "Sehore",
    "Gwalior",
    "Ujjain",
    "Bhind",
    "Damoh",
    "Morena",
    "Tikamgarh",
    "Ratlam",
    "Guna",
    "Katni",
    "Narmadapuram",
    "Sidhi",
    "Shajapur",
    "Sagar",
    "Balaghat",
    "Chhindwara",
    "Vidisha",
    "Barwani",
    "Shivpuri",
    "Khandwa",
    "Shahdol",
    "Mandla",
    "Satna",
    "Betul",
    "Khargone",
    "Dhar",
    "Jhabua",
    "Anuppur",
    "Rewa",
    "Alirajpur",
    "Raisen",
    "Rajgarh",
    "Niwari",
    "Narsinghpur",
    "Panna",
    "Neemuch",
    "Maihar",
    "Dewas",
    "Dindori",
    "Burhanpur",
    "Harda",
    "Datia",
    "Mauganj",
    "Agar Malwa",
    "Ashoknagar",
    "Bharuch",
    "Banaskantha",
    "Surendranagar",
    "Vadodara",
    "Anand",
    "Ahmedabad",
    "Surat",
    "Valsad",
    "Panchmahals",
    "Rajkot",
    "Bhavnagar",
    "Kachchh",
    "Gandhinagar",
    "Amreli",
    "Mahesana",
    "Jamnagar",
    "Kheda",
    "Morbi",
    "Sabarkantha",
    "Navsari",
    "Dahod",
    "Junagadh",
    "Porbandar",
    "Aravalli",
    "Gir Somnath",
    "Chhotaudepur",
    "Patan",
    "Botad",
    "Narmada",
    "Mahisagar",
    "Tapi",
    "Dadra And Nagar Haveli",
    "Daman",
    "Beed",
    "Nashik",
    "Mumbai",
    "Mumbai Suburban",
    "Thane",
    "Kolhapur",
    "Pune",
    "Amravati",
    "Satara",
    "Ahilyanagar",
    "Ratnagiri",
    "Chhatrapati Sambhaji Nagar",
    "Nagpur",
    "Yavatmal",
    "Sangli",
    "Raigad",
    "Chandrapur",
    "Dhule",
    "Sindhudurg",
    "Jalna",
    "Palghar",
    "Solapur",
    "Nanded",
    "Buldhana",
    "Gondia",
    "Nandurbar",
    "Akola",
    "Wardha",
    "Bhandara",
    "Latur",
    "Jalgaon",
    "Washim",
    "Parbhani",
    "Hingoli",
    "Gadchiroli",
    "Dharashiv",
    "Bengaluru Urban",
    "Mysuru",
    "Bidar",
    "Ballari",
    "Belagavi",
    "Mandya",
    "Bagalkote",
    "Dharwad",
    "Kodagu",
    "Chikkaballapur",
    "Raichur",
    "Hassan",
    "Chamarajanagar",
    "Dakshina Kannada",
    "Uttara Kannada",
    "Bengaluru Rural",
    "Udupi",
    "Shivamogga",
    "Kolar",
    "Chikkamagaluru",
    "Vijayapura",
    "Davanagere",
    "Yadgiri",
    "Kalaburagi",
    "Chitradurga",
    "Gadag",
    "Tumakuru",
    "Haveri",
    "Ramanagara",
    "Koppal",
    "Vijayanagara",
    "North Goa",
    "South Goa",
    "Ernakulam",
    "Kannur",
    "Kasargod",
    "Kottayam",
    "Malappuram",
    "Palakkad",
    "Kozhikode",
    "Thrissur",
    "Idukki",
    "Wayanad",
    "Thiruvananthapuram",
    "Alappuzha",
    "Pathanamthitta",
    "Kollam",
    "Chennai",
    "Kancheepuram",
    "Salem",
    "Coimbatore",
    "Tiruvallur",
    "Krishnagiri",
    "Tiruvarur",
    "Dharmapuri",
    "Chengalpattu",
    "Tirunelveli",
    "Vellore",
    "Thoothukudi",
    "Ranipet",
    "Tiruchirappalli",
    "Virudhunagar",
    "Tiruvannamalai",
    "Sivaganga",
    "Viluppuram",
    "Dindigul",
    "Tenkasi",
    "Tiruppur",
    "Thanjavur",
    "Madurai",
    "Namakkal",
    "Erode",
    "Ariyalur",
    "Ramanathapuram",
    "Nagapattinam",
    "Cuddalore",
    "Theni",
    "Karur",
    "Mayiladuthurai",
    "Pudukkottai",
    "Kallakurichi",
    "Tirupathur",
    "Kanniyakumari",
    "The Nilgiris",
    "Perambalur",
    "Puducherry",
    "Karaikal",
    "Yanam",
    "South Andaman",
    "North and Middle Andaman",
    "Hyderabad",
    "Sangareddy",
    "Nizamabad",
    "Medchal Malkajgiri",
    "Rangareddy",
    "Doda",
    "Chamba",
    "Anjaw",
    "Kurung Kumey",
    "West Siang",
    "Tengnoupal",
    "Jiribam",
    "Kakching",
    "Champhai",
    "Khowai",
    "South Garo Hills",
    "Hojai",
    "Dima Hasao",
    "Udalguri",
    "Simdega",
    "Jharsuguda",
    "Nuapada",
    "Gaurela Pendra Marwahi",
    "North Bastar Kanker",
    "Devbhumi Dwarka",
    "Dangs",
    "Mahe",
    "Hanumakonda",
    "Nalgonda",
    "Yadadri Bhuvanagiri",
    "Nagarkurnool",
    "Khammam",
    "Siddipet",
    "Jagtial",
    "Warangal",
    "Karimnagar",
    "Nirmal",
    "Peddapalli",
    "Mahabubnagar",
    "Mancherial",
    "Rajanna Sircilla",
    "Kamareddy",
    "Adilabad",
    "Suryapet",
    "Vikarabad",
    "Bhadradri Kothagudem",
    "Kumuram Bheem Asifabad",
    "Mahabubabad",
    "Narayanpet",
    "Jogulamba Gadwal",
    "Dr BR Ambedkar Konaseema",
    "Visakhapatnam",
    "NTR",
    "East Godavari",
    "Tirupati",
    "Sri Sathyasai",
    "Kakinada",
    "Srikakulam",
    "Anakapalli",
    "Sri Potti Sriramulu Nellore",
    "West Godavari",
    "Ananthapuramu",
    "Chittoor",
    "Annamayya",
    "Eluru",
    "Bapatla",
    "Guntur",
    "Palnadu",
    "YSR",
    "Prakasam",
    "Nandyal",
    "Kurnool",
    "Vizianagaram",
    "Krishna",
    "Leh Ladakh",
    "Kargil",
    "Pakyong",
    "Soreng",
    "West Kameng",
    "Pakke Kessang",
    "Dhalai",
    "Bajali",
    "Khunti",
    "Narayanpur",
    "Lakshadweep",
    "Medak",
    "Jayashankar Bhupalpally",
    "Mulugu",
    "Wanaparthy",
    "Rudraprayag",
    "Tawang",
    "Chandel",
    "Sheopur",
    "Jangaon",
    "Parvathipuram Manyam",
    "Upper Subansiri",
    "Chumoukedima",
    "Bishnupur",
    "Salumber",
    "Namsai",
    "Upper Siang",
    "Tuensang",
    "Ukhrul",
    "South Tripura",
    "Eastern West Khasi Hills",
    "Gajapati",
    "Diu",
    "Shamator",
    "Mokokchung",
    "Ri Bhoi",
    "Umaria",
    "Lepa Rada",
    "Phek",
    "Noney",
    "Hnahthial",
    "Lunglei",
    "Kolasib",
    "Alluri Sitharama Raju",
    "Mon",
    "Siaha",
    "Longding",
    "East Kameng",
    "Mamit",
    "Noklak",
    "Mangan",
    "Khawzawl",
    "Kamle",
    "South West Garo Hills",
    "Kiphire",
    "Peren",
    "Kangpokpi",
    "Serchhip",
    "Senapati",
    "Tirap",
    "Tamenglong",
    "Lahaul And Spiti",
    "Bichom",
    "not found",
    "Shi Yomi",
    "Tseminyu",
    "Wokha",
    "South West Khasi Hills",
    "Longleng",
    "Kamjong",
    "Kra Daadi",
    "Saitual",
    "Lower Siang",
    "Dibang Valley",
    "Nicobar",
    "Niuland",
    "Bardhaman",
  ],
};

export const gstMapping = [
  {
    name: "Jammu & Kashmir",
    children: [
      "Jammu",
      "Budgam",
      "Samba",
      "Pulwama",
      "Ganderbal",
      "Srinagar",
      "Ramban",
      "Bandipore",
      "Baramulla",
      "Shopian",
      "Kupwara",
      "Anantnag",
      "Reasi",
      "Udhampur",
      "Kishtwar",
      "Kulgam",
      "Rajouri",
      "Poonch",
      "Kathua",
      "Doda",
      "Leh Ladakh",
      "Kargil",
    ],
  },
  {
    name: "Himachal Pradesh",
    children: [
      "Shimla",
      "Kangra",
      "Kullu",
      "Una",
      "Solan",
      "Bilaspur",
      "Mandi",
      "Sirmaur",
      "Hamirpur",
      "Kinnaur",
      "Chamba",
      "Lahaul And Spiti",
    ],
  },
  {
    name: "Punjab",
    children: [
      "Ludhiana",
      "Jalandhar",
      "Amritsar",
      "SAS Nagar",
      "Pathankot",
      "Fatehgarh Sahib",
      "Malerkotla",
      "Bathinda",
      "Sri Muktsar Sahib",
      "Sangrur",
      "Faridkot",
      "Kapurthala",
      "Patiala",
      "Hoshiarpur",
      "Mansa",
      "Rupnagar",
      "Fazilka",
      "Gurdaspur",
      "Ferozepur",
      "Barnala",
      "Shaheed Bhagat Singh Nagar",
      "Tarn Taran",
      "Moga",
    ],
  },
  {
    name: "Chandigarh",
    children: ["Chandigarh"],
  },
  {
    name: "Uttarakhand",
    children: [
      "Haridwar",
      "Nainital",
      "Dehradun",
      "Udham Singh Nagar",
      "Champawat",
      "Tehri Garhwal",
      "Almora",
      "Pithoragarh",
      "Uttarkashi",
      "Bageshwar",
      "Chamoli",
      "Pauri Garhwal",
      "Rudraprayag",
    ],
  },
  {
    name: "Haryana",
    children: [
      "Faridabad",
      "Gurugram",
      "Hisar",
      "Panchkula",
      "Palwal",
      "Sonipat",
      "Kurukshetra",
      "Fatehabad",
      "Karnal",
      "Kaithal",
      "Nuh",
      "Ambala",
      "Mahendragarh",
      "Yamunanagar",
      "Sirsa",
      "Jind",
      "Bhiwani",
      "Rohtak",
      "Panipat",
      "Charkhi Dadri",
      "Jhajjar",
      "Rewari",
    ],
  },
  {
    name: "Delhi",
    children: [
      "Central Delhi",
      "South Delhi",
      "North West Delhi",
      "North East Delhi",
      "South West Delhi",
      "East Delhi",
      "New Delhi",
      "South East Delhi",
      "West Delhi",
      "North Delhi",
      "Shahdara",
    ],
  },
  {
    name: "Rajasthan",
    children: [
      "Neem Ka Thana",
      "Bhilwara",
      "Jaipur",
      "Deeg",
      "Bikaner",
      "Jodhpur",
      "Kota",
      "Deedwana Kuchaman",
      "Alwar",
      "Khairthal Tijara",
      "Sikar",
      "Jaipur Rural",
      "Sirohi",
      "Kotputli Behror",
      "Rajsamand",
      "Ajmer",
      "Balotra",
      "Sri Ganganagar",
      "Dholpur",
      "Jhunjhunu",
      "Nagaur",
      "Beawar",
      "Chittorgarh",
      "Udaipur",
      "Sanchore",
      "Jaisalmer",
      "Phalodi",
      "Sawai Madhopur",
      "Tonk",
      "Pali",
      "Pratapgarh",
      "Hanumangarh",
      "Churu",
      "Banswara",
      "Karauli",
      "Jodhpur Rural",
      "Dungarpur",
      "Barmer",
      "Baran",
      "Jalore",
      "Shahpura",
      "Bundi",
      "Anupgarh",
      "Dudu",
      "Dausa",
      "Bharatpur",
      "Kekri",
      "Jhalawar",
      "Gangapur City",
      "Salumber",
    ],
  },
  {
    name: "Uttar Pradesh",
    children: [
      "Raebareli",
      "Gautambuddha Nagar",
      "Aligarh",
      "Lucknow",
      "Prayagraj",
      "Bulandshahr",
      "Hapur",
      "Kanpur Nagar",
      "Varanasi",
      "Gorakhpur",
      "Fatehpur",
      "Agra",
      "Ghaziabad",
      "Moradabad",
      "Mathura",
      "Basti",
      "Deoria",
      "Meerut",
      "Saharanpur",
      "Bareilly",
      "Rampur",
      "Siddharthnagar",
      "Ghazipur",
      "Kaushambi",
      "Gonda",
      "Muzaffarnagar",
      "Mau",
      "Kushinagar",
      "Amroha",
      "Chandauli",
      "Mirzapur",
      "Ayodhya",
      "Jhansi",
      "Bhadohi",
      "Bijnor",
      "Etawah",
      "Bagpat",
      "Kanpur Dehat",
      "Lakhimpur Kheri",
      "Firozabad",
      "Sambhal",
      "Jaunpur",
      "Shamli",
      "Sitapur",
      "Banda",
      "Kasganj",
      "Etah",
      "Maharajganj",
      "Ballia",
      "Azamgarh",
      "Budaun",
      "Balrampur",
      "Ambedkar Nagar",
      "Barabanki",
      "Lalitpur",
      "Mainpuri",
      "Shravasti",
      "Hardoi",
      "Sultanpur",
      "Farrukhabad",
      "Pilibhit",
      "Jalaun",
      "Auraiya",
      "Unnao",
      "Sonbhadra",
      "Shahjahanpur",
      "Hathras",
      "Bahraich",
      "Chitrakoot",
      "Amethi",
      "Sant Kabir Nagar",
      "Kannauj",
      "Mahoba",
    ],
  },
  {
    name: "Bihar",
    children: [
      "Patna",
      "Samastipur",
      "Pashchim Champaran",
      "Vaishali",
      "Muzaffarpur",
      "Bhagalpur",
      "Darbhanga",
      "Khagaria",
      "Begusarai",
      "Rohtas",
      "Purnea",
      "Kishanganj",
      "Nawada",
      "Siwan",
      "Aurangabad",
      "Katihar",
      "Purbi Champaran",
      "Gaya",
      "Jehanabad",
      "Jamui",
      "Sitamarhi",
      "Bhojpur",
      "Madhubani",
      "Buxar",
      "Nalanda",
      "Munger",
      "Araria",
      "Madhepura",
      "Lakhisarai",
      "Saran",
      "Gopalganj",
      "Sheohar",
      "Kaimur",
      "Supaul",
      "Sheikhpura",
      "Saharsa",
      "Banka",
      "Arwal",
    ],
  },
  {
    name: "Sikkim",
    children: ["Gangtok", "Gyalshing", "Namchi", "Pakyong", "Soreng", "Mangan"],
  },
  {
    name: "Arunachal Pradesh",
    children: [
      "Changlang",
      "Papum Pare",
      "Keyi Panyor",
      "Lower Subansiri",
      "Itanagar Capital Complex",
      "Siang",
      "East Siang",
      "Lower Dibang Valley",
      "Lohit",
      "Anjaw",
      "Kurung Kumey",
      "West Siang",
      "West Kameng",
      "Pakke Kessang",
      "Tawang",
      "Namsai",
      "Upper Siang",
      "Lepa Rada",
      "Longding",
      "East Kameng",
      "Kamle",
      "Tirap",
      "Shi Yomi",
      "Kra Daadi",
      "Lower Siang",
      "Dibang Valley",
      "Upper Subansiri",
    ],
  },
  {
    name: "Nagaland",
    children: [
      "Zunheboto",
      "Dimapur",
      "Kohima",
      "Chumoukedima",
      "Shamator",
      "Mokokchung",
      "Mon",
      "Noklak",
      "Kiphire",
      "Peren",
      "Tseminyu",
      "Wokha",
      "Longleng",
      "Niuland",
      "Tuensang",
      "Phek",
    ],
  },
  {
    name: "Manipur",
    children: [
      "Imphal West",
      "Thoubal",
      "Churachandpur",
      "Imphal East",
      "Tengnoupal",
      "Jiribam",
      "Kakching",
      "Chandel",
      "Bishnupur",
      "Noney",
      "Kangpokpi",
      "Senapati",
      "Tamenglong",
      "Ukhrul",
      "Kamjong",
    ],
  },
  {
    name: "Mizoram",
    children: [
      "Aizawl",
      "Lawngtlai",
      "Champhai",
      "Hnahthial",
      "Lunglei",
      "Kolasib",
      "Siaha",
      "Mamit",
      "Khawzawl",
      "Serchhip",
      "Saitual",
    ],
  },
  {
    name: "Tripura",
    children: [
      "North Tripura",
      "Unakoti",
      "Sepahijala",
      "West Tripura",
      "Gomati",
      "Dhalai",
      "South Tripura",
      "Khowai",
    ],
  },
  {
    name: "Meghalaya",
    children: [
      "East Khasi Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
      "West Garo Hills",
      "North Garo Hills",
      "East Garo Hills",
      "East Jaintia Hills",
      "Eastern West Khasi Hills",
      "Ri Bhoi",
      "South West Garo Hills",
      "South West Khasi Hills",
    ],
  },
  {
    name: "Assam",
    children: [
      "Kamrup Metropolitan",
      "Kokrajhar",
      "Morigaon",
      "Nalbari",
      "Tinsukia",
      "Dibrugarh",
      "Bongaigaon",
      "Nagaon",
      "South Salmara Mankachar",
      "Golaghat",
      "Cachar",
      "Baksa",
      "Hailakandi",
      "Lakhimpur",
      "Karimganj",
      "Biswanath",
      "Dhemaji",
      "Kamrup",
      "Chirang",
      "Jorhat",
      "Barpeta",
      "Karbi Anglong",
      "West Karbi Anglong",
      "Dhubri",
      "Tamulpur",
      "Majuli",
      "Sivasagar",
      "Charaideo",
      "Goalpara",
      "Sonitpur",
      "Darrang",
      "Hojai",
      "Dima Hasao",
      "Udalguri",
      "Bajali",
    ],
  },
  {
    name: "West Bengal",
    children: [
      "Kolkata",
      "Purba Medinipur",
      "Malda",
      "Howrah",
      "North Twenty Four Parganas",
      "Darjeeling",
      "South Twenty Four Parganas",
      "Birbhum",
      "Paschim Bardhaman",
      "Bankura",
      "Murshidabad",
      "Hooghly",
      "Dakshin Dinajpur",
      "Paschim Medinipur",
      "Nadia",
      "Purba Bardhaman",
      "Uttar Dinajpur",
      "Alipurduar",
      "Cooch Behar",
      "Jalpaiguri",
      "Jhargram",
      "Purulia",
      "Kalimpong",
      "Bardhaman",
    ],
  },
  {
    name: "Jharkhand",
    children: [
      "East Singhbhum",
      "Dhanbad",
      "Ranchi",
      "Hazaribag",
      "Lohardaga",
      "Bokaro",
      "Ramgarh",
      "Koderma",
      "Godda",
      "Dumka",
      "Pakur",
      "Chatra",
      "Palamu",
      "Deoghar",
      "Jamtara",
      "Sahibganj",
      "Giridih",
      "Garhwa",
      "Latehar",
      "West Singhbhum",
      "Seraikela Kharsawan",
      "Gumla",
      "Simdega",
      "Khunti",
    ],
  },
  {
    name: "Odisha",
    children: [
      "Angul",
      "Khordha",
      "Ganjam",
      "Nabarangpur",
      "Koraput",
      "Puri",
      "Sambalpur",
      "Cuttack",
      "Baleswar",
      "Jajpur",
      "Bargarh",
      "Kalahandi",
      "Mayurbhanj",
      "Rayagada",
      "Nayagarh",
      "Kendujhar",
      "Jagatsinghpur",
      "Bhadrak",
      "Balangir",
      "Dhenkanal",
      "Boudh",
      "Kendrapara",
      "Malkangiri",
      "Deogarh",
      "Kandhamal",
      "Sundargarh",
      "Subarnapur",
      "Jharsuguda",
      "Nuapada",
      "Gajapati",
    ],
  },
  {
    name: "Chhattisgarh",
    children: [
      "Korba",
      "Raipur",
      "Durg",
      "Raigarh",
      "Bijapur",
      "Dantewada",
      "Rajnandgaon",
      "Balodabazar Bhatapara",
      "Janjgir Champa",
      "Mahasamund",
      "Sukma",
      "Bastar",
      "Sakti",
      "Surajpur",
      "Kabirdham",
      "Surguja",
      "Balod",
      "Manendragarh Chirmiri Bharatpur",
      "Korea",
      "Gariaband",
      "Kondagaon",
      "Balrampur Ramanujganj",
      "Sarangarh Bilaigarh",
      "Dhamtari",
      "Khairagarh Chhuikhadan Gandai",
      "Mohla Manpur Ambagarh Chouki",
      "Jashpur",
      "Bemetara",
      "Mungeli",
      "Gaurela Pendra Marwahi",
      "North Bastar Kanker",
      "Narayanpur",
    ],
  },
  {
    name: "Madhya Pradesh",
    children: [
      "Indore",
      "Bhopal",
      "Singrauli",
      "Jabalpur",
      "Seoni",
      "Mandsaur",
      "Chhatarpur",
      "Pandhurna",
      "Sehore",
      "Gwalior",
      "Ujjain",
      "Bhind",
      "Damoh",
      "Morena",
      "Tikamgarh",
      "Ratlam",
      "Guna",
      "Katni",
      "Narmadapuram",
      "Sidhi",
      "Shajapur",
      "Sagar",
      "Balaghat",
      "Chhindwara",
      "Vidisha",
      "Barwani",
      "Shivpuri",
      "Khandwa",
      "Shahdol",
      "Mandla",
      "Satna",
      "Betul",
      "Khargone",
      "Dhar",
      "Jhabua",
      "Anuppur",
      "Rewa",
      "Alirajpur",
      "Raisen",
      "Rajgarh",
      "Niwari",
      "Narsinghpur",
      "Panna",
      "Neemuch",
      "Maihar",
      "Dewas",
      "Dindori",
      "Burhanpur",
      "Harda",
      "Datia",
      "Mauganj",
      "Agar Malwa",
      "Ashoknagar",
      "Umaria",
      "Sheopur",
    ],
  },
  {
    name: "Gujarat",
    children: [
      "Bharuch",
      "Banaskantha",
      "Surendranagar",
      "Vadodara",
      "Anand",
      "Ahmedabad",
      "Surat",
      "Valsad",
      "Panchmahals",
      "Rajkot",
      "Bhavnagar",
      "Kachchh",
      "Gandhinagar",
      "Amreli",
      "Mahesana",
      "Jamnagar",
      "Kheda",
      "Morbi",
      "Sabarkantha",
      "Navsari",
      "Dahod",
      "Junagadh",
      "Porbandar",
      "Aravalli",
      "Gir Somnath",
      "Chhotaudepur",
      "Patan",
      "Botad",
      "Narmada",
      "Mahisagar",
      "Tapi",
      "Devbhumi Dwarka",
      "Dangs",
    ],
  },
  {
    name: "Daman and Diu",
    children: ["Daman", "Diu"],
  },
  {
    name: "Dadra and Nagar Haveli",
    children: ["Dadra And Nagar Haveli"],
  },
  {
    name: "Maharashtra",
    children: [
      "Beed",
      "Nashik",
      "Mumbai",
      "Mumbai Suburban",
      "Thane",
      "Kolhapur",
      "Pune",
      "Amravati",
      "Satara",
      "Ahilyanagar",
      "Ratnagiri",
      "Chhatrapati Sambhaji Nagar",
      "Nagpur",
      "Yavatmal",
      "Sangli",
      "Raigad",
      "Chandrapur",
      "Dhule",
      "Sindhudurg",
      "Jalna",
      "Palghar",
      "Solapur",
      "Nanded",
      "Buldhana",
      "Gondia",
      "Nandurbar",
      "Akola",
      "Wardha",
      "Bhandara",
      "Latur",
      "Jalgaon",
      "Washim",
      "Parbhani",
      "Hingoli",
      "Gadchiroli",
      "Dharashiv",
    ],
  },
  {
    name: "Karnataka",
    children: [
      "Bengaluru Urban",
      "Mysuru",
      "Bidar",
      "Ballari",
      "Belagavi",
      "Mandya",
      "Bagalkote",
      "Dharwad",
      "Kodagu",
      "Chikkaballapur",
      "Raichur",
      "Hassan",
      "Chamarajanagar",
      "Dakshina Kannada",
      "Uttara Kannada",
      "Bengaluru Rural",
      "Udupi",
      "Shivamogga",
      "Kolar",
      "Chikkamagaluru",
      "Vijayapura",
      "Davanagere",
      "Yadgiri",
      "Kalaburagi",
      "Chitradurga",
      "Gadag",
      "Tumakuru",
      "Haveri",
      "Ramanagara",
      "Koppal",
      "Vijayanagara",
    ],
  },
  {
    name: "Goa",
    children: ["North Goa", "South Goa"],
  },
  {
    name: "Lakshadweep",
    children: ["Lakshadweep"],
  },
  {
    name: "Kerala",
    children: [
      "Ernakulam",
      "Kannur",
      "Kasargod",
      "Kottayam",
      "Malappuram",
      "Palakkad",
      "Kozhikode",
      "Thrissur",
      "Idukki",
      "Wayanad",
      "Thiruvananthapuram",
      "Alappuzha",
      "Pathanamthitta",
      "Kollam",
    ],
  },
  {
    name: "Tamil Nadu",
    children: [
      "Chennai",
      "Kancheepuram",
      "Salem",
      "Coimbatore",
      "Tiruvallur",
      "Krishnagiri",
      "Tiruvarur",
      "Dharmapuri",
      "Chengalpattu",
      "Tirunelveli",
      "Vellore",
      "Thoothukudi",
      "Ranipet",
      "Tiruchirappalli",
      "Virudhunagar",
      "Tiruvannamalai",
      "Sivaganga",
      "Viluppuram",
      "Dindigul",
      "Tenkasi",
      "Tiruppur",
      "Thanjavur",
      "Madurai",
      "Namakkal",
      "Erode",
      "Ariyalur",
      "Ramanathapuram",
      "Nagapattinam",
      "Cuddalore",
      "Theni",
      "Karur",
      "Mayiladuthurai",
      "Pudukkottai",
      "Kallakurichi",
      "Tirupathur",
      "Kanniyakumari",
      "The Nilgiris",
      "Perambalur",
    ],
  },
  {
    name: "Puducherry",
    children: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  },
  {
    name: "Andaman and Nicobar Islands",
    children: ["South Andaman", "North and Middle Andaman", "Nicobar"],
  },
  {
    name: "Telangana",
    children: [
      "Hyderabad",
      "Sangareddy",
      "Nizamabad",
      "Medchal Malkajgiri",
      "Rangareddy",
      "Hanumakonda",
      "Nalgonda",
      "Yadadri Bhuvanagiri",
      "Nagarkurnool",
      "Khammam",
      "Siddipet",
      "Jagtial",
      "Warangal",
      "Karimnagar",
      "Nirmal",
      "Peddapalli",
      "Mahabubnagar",
      "Mancherial",
      "Rajanna Sircilla",
      "Kamareddy",
      "Adilabad",
      "Suryapet",
      "Vikarabad",
      "Bhadradri Kothagudem",
      "Kumuram Bheem Asifabad",
      "Mahabubabad",
      "Narayanpet",
      "Jogulamba Gadwal",
      "Medak",
      "Jayashankar Bhupalpally",
      "Mulugu",
      "Wanaparthy",
      "Jangaon",
    ],
  },
  {
    name: "Andhra Pradesh (New)",
    children: [
      "Dr BR Ambedkar Konaseema",
      "Visakhapatnam",
      "NTR",
      "East Godavari",
      "Tirupati",
      "Sri Sathyasai",
      "Kakinada",
      "Srikakulam",
      "Anakapalli",
      "Sri Potti Sriramulu Nellore",
      "West Godavari",
      "Ananthapuramu",
      "Chittoor",
      "Annamayya",
      "Eluru",
      "Bapatla",
      "Guntur",
      "Palnadu",
      "YSR",
      "Prakasam",
      "Nandyal",
      "Kurnool",
      "Vizianagaram",
      "Krishna",
      "Alluri Sitharama Raju",
      "Parvathipuram Manyam",
    ],
  },
];

const accessJson = {
  gst: {
    Chandigarh: ["Chandigarh"],
    Uttarakhand: [
      "Haridwar",
      "Nainital",
      "Dehradun",
      "Udham Singh Nagar",
      "Champawat",
      "Tehri Garhwal",
      "Almora",
      "Pithoragarh",
      "Uttarkashi",
      "Bageshwar",
      "Chamoli",
      "Pauri Garhwal",
      "Rudraprayag",
    ],
  },
  mca: {
    Chandigarh: ["Chandigarh"],
    Uttarakhand: [
      "Haridwar",
      "Nainital",
      "Dehradun",
      "Udham Singh Nagar",
      "Champawat",
      "Tehri Garhwal",
      "Almora",
      "Pithoragarh",
      "Uttarkashi",
      "Bageshwar",
      "Chamoli",
      "Pauri Garhwal",
      "Rudraprayag",
    ],
  },
  iec: {
    Chandigarh: [],
    Uttarakhand: [],
  },
};

export const mcaRocAndCitySubscriptionsMapping = {
  "ROC Delhi": {
    cities: [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "West Delhi",
      "Anjaw Delhi",
      "SHAKARPUR",
      "Wokha Delhi",
    ],
  },
  "ROC Mumbai": {
    state: "Maharashtra",
    cities: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Barshi",
      "Bhiwandi-Nizampur",
      "Chandrapur",
      "Dhule",
      "Ichalkaranji",
      "Jalgaon",
      "Jalna",
      "Kalyan-Dombivli",
      "Kolhapur",
      "Latur",
      "Malegaon",
      "Mira-Bhayandar",
      "Mumbai",
      "Nagpur",
      "Nanded-Waghala",
      "Nashik",
      "Navi Mumbai",
      "Osmanabad",
      "Panvel",
      "Parbhani",
      "Pimpri-Chinchwad",
      "Pune",
      "Ratnagiri",
      "Sangli-Miraj-Kupwad",
      "Satara",
      "Solapur",
      "Thane",
      "Ulhasnagar",
      "Vasai-Virar",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  "ROC Bangalore": {
    state: "Karnataka",
    cities: [
      "Bengaluru Urban",
      "Bengaluru Rural",
      "Bagalkote",
      "Ballari",
      "Belagavi",
      "Bidar",
      "Chamarajanagar",
      "Chikkaballapur",
      "Chikkamagaluru",
      "Chitradurga",
      "Dakshina Kannada",
      "Davanagere",
      "Dharwad",
      "Gadag",
      "Hassan",
      "Haveri",
      "Bangalore",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru",
      "Raichur",
      "Ramanagara",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Uttara Kannada",
      "Vijayapura",
      "Yadgir",
    ],
  },
  "ROC Jaipur": {
    state: "Rajasthan",
    cities: [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dholpur",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Sri Ganganagar",
      "Tonk",
      "Udaipur",
    ],
  },
  "ROC Ernakulam": {
    state: "Kerala",
    cities: [
      "Thiruvananthapuram",
      "Kollam",
      "Pathanamthitta",
      "Alappuzha",
      "Kottayam",
      "Idukki",
      "Ernakulam",
      "Thrissur",
      "Palakkad",
      "Malappuram & Kozhikode",
      "Kannur & Wayanad",
      "Kasaragod",
    ],
  },
  "ROC Patna": {
    state: "Bihar",
    cities: [
      "Arwal",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Buxar",
      "Bettiah",
      "Darbhanga",
      "Gaya",
      "Jamalpur",
      "Katihar",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas (Sasaram)",
      "Saran (Chhapra)",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Samastipur",
      "Vaishali (Hajipur)",
      "West",
      "East",
      "Madhepura",
      "Saharsa",
      "Arrah (Bhojpur)",
      "Aurangabad",
      "Khagaria",
      "Sheikhpura",
      "Lakhisarai",
      "Gopalganj",
      "Jamui",
      "Kaimur (Bhabua)",
      "Madhubani",
      "Munger",
      "Nalanda",
      "Nawada",
    ],
  },
  "ROC Gwalior": {
    state: "Madhya Pradesh",
    cities: [
      "Agar Malwa",
      "Alirajpur",
      "Ashoknagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandsaur",
      "Morena",
      "Nagda",
      "Neemuch",
      "Panna",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
  },
  "ROC Ahmedabad": {
    state: "Gujarat",
    cities: [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Bhavnagar",
      "Bharuch",
      "Dahod",
      "Gandhinagar",
      "Godhra",
      "Jamnagar",
      "Junagadh",
      "Kheda",
      "Mahesana",
      "Mehsana",
      "Nadiad",
      "Navsari",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Surat",
      "Surendranagar",
      "Vadodara",
      "Valsad",
      "Vapi",
      "Bhuj",
      "Morbi",
      "Palanpur",
      "Vyara",
    ],
  },
  "ROC Kanpur": {
    state: "Uttar Pradesh",
    cities: [
      "Agra",
      "Aligarh",
      "Allahabad (Prayagraj)",
      "Amroha",
      "Azamgarh",
      "Bareilly",
      "Basti",
      "Ballia",
      "Banda",
      "Barabanki",
      "Badaun",
      "Bulandshahr",
      "Chandauli",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad (Ayodhya)",
      "Farrukhabad",
      "Fatehpur",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Rae Bareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shravasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
  "ROC Uttarakhand": {
    state: "Uttarakhand",
    cities: [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar (Haldwani)",
      "Champawat",
      "Pithoragarh",
      "Rishikesh",
      "Kotdwar",
      "Roorkee",
    ],
  },
  "ROC Hyderabad": {
    state: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Karimnagar",
      "Nizamabad",
      "Khammam",
      "Mahbubnagar",
      "Ramagundam",
      "Siddipet",
      "Nalgonda",
      "Adilabad",
      "Miryalaguda",
      "Suryapet",
      "Jagtial",
      "Bhongir (Bhuvanagiri)",
      "Kothagudem",
      "Vikarabad",
      "Kamareddy",
      "Mancherial",
      "Medak",
      "Mulugu",
      "Nagarkurnool",
      "Wanaparthy",
      "Jogulamba Gadwal",
      "Jayashankar Bhupalpally",
      "Peddapalli",
    ],
  },
  "ROC Cuttack": {
    state: "Orissa",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur (Brahmapur)",
      "Puri",
      "Sambalpur",
      "Balasore (Baleshwar)",
      "Jharsuguda",
      "Jajpur",
      "Koraput",
      "Baripada",
      "Angul",
      "Dhenkanal",
      "Keonjhar (Kendujhar)",
      "Balangir",
      "Bhadrak",
      "Jagatsinghpur",
      "Kendrapara",
      "Malkangiri",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Phulbani (Kandhamal)",
      "Sundargarh",
      "Deogarh",
      "Ganjam",
      "Kalahandi",
      "Jajapur",
    ],
  },
  "ROC Guwahati": {
    state: "Assam",
    cities: [
      "Kamrup",
      "Cachar",
      "Dibrugarh",
      "Guwahati",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Barpeta",
      "Silchar",
      "Sivasagar",
      "Sonitpur",
      "Dhubri",
      "Kokrajhar",
      "Bongaigaon",
      "Goalpara",
      "Morigaon",
      "Nalbari",
      "Karbi Anglong",
      "Chirang",
      "Hojai",
      "Udalguri",
    ],
  },
  "ROC Kolkata": {
    state: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Asansol",
      "Siliguri",
      "Durgapur",
      "Bardhaman",
      "Malda",
      "Kharagpur",
      "Jalpaiguri",
      "Santiniketan",
      "Haldia",
      "Raiganj",
      "Tamluk",
      "Balurghat",
      "Bishnupur",
      "Chandannagar",
      "Darjeeling",
      "Krishnanagar",
      "Berhampore",
      "Bankura",
      "Cooch Behar",
      "Gangarampur",
      "Purulia",
      "Suri",
      "South 24 Pargana",
    ],
  },
  "ROC Vijayawada": {
    state: "Andhra Pradesh",
    cities: [
      "Anantapur",
      "Chittoor",
      "East Godavari (Rajahmundry)",
      "Guntur",
      "Kadapa (Cuddapah)",
      "Krishna (Machilipatnam)",
      "Kurnool",
      "Nellore",
      "Prakasam (Ongole)",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari (Eluru)",
    ],
  },
  "ROC Chennai": {
    state: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Salem",
      "Tiruchirappalli (Trichy)",
      "Erode",
      "Tirunelveli",
      "Vellore",
      "Thoothukudi (Tuticorin)",
      "Dindigul",
      "Thanjavur",
      "Cuddalore",
      "Karur",
      "Tiruppur",
      "Kanchipuram",
      "Hosur",
      "Sivakasi",
      "Nagercoil",
      "Udhagamandalam (Ooty)",
      "Mayiladuthurai",
      "Ramanathapuram",
      "Theni",
      "Namakkal",
      "Dharmapuri",
      "Nagapattinam",
      "Krishnagiri",
      "Villupuram",
      "Tiruvannamalai",
      "Kumbakonam",
      "Pudukkottai",
      "Tirupattur",
      "Arakkonam",
      "Ambur",
    ],
  },
  "ROC Himachal Pradesh": {
    state: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Palampur",
      "Baddi",
      "Nahan",
      "Paonta Sahib",
      "Sundarnagar",
      "Chamba",
      "Una",
      "Kullu",
      "Hamirpur",
      "Bilaspur",
      "Manali",
    ],
  },
  "ROC Chandigarh": {
    states: ["Punjab", "Haryana"],
    cities: [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Pathankot",
      "Patiala",
      "Rupnagar (Ropar)",
      "Sahibzada(Mohali)",
      "Sangrur",
      "Shahid (Nawanshahr)",
      "Sri Muktsar Sahib",
      "Tarn Taran",
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurugram",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
  },
  "ROC Jammu": {
    state: "Jammu & Kashmir",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Sopore",
      "Udhampur",
      "Kathua",
      "Kupwara",
      "Poonch",
      "Rajouri",
      "Kargil",
      "Leh",
      "Pulwama",
      "Ganderbal",
      "Bandipora",
      "Shopian",
      "Reasi",
      "Doda",
      "Ramban",
      "Kishtwar",
      "Budgam",
    ],
  },
  "ROC Goa": {
    state: "Goa",
    cities: ["North Goa", "South Goa"],
  },
  "ROC Chhattisgarh": {
    state: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bilaspur",
      "Durg",
      "Korba",
      "Rajnandgaon",
      "Bhilai",
      "Jagdalpur",
      "Ambikapur",
      "Dantewada",
      "Mahasamund",
      "Kawardha",
      "Kanker",
      "Kabirdham (Kawardha)",
      "Janjgir-Champa",
      "Raigarh",
      "Surajpur",
      "Jashpur Nagar",
      "Balod",
      "Gariaband",
      "Baloda Bazar",
      "Dhamtari",
      "Mungeli",
      "Bijapur",
      "Kondagaon",
      "Sukma",
    ],
  },
  "ROC Jharkhand": {
    state: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro Steel City",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Lohardaga",
      "Chaibasa",
      "Dumka",
      "Medininagar (Daltonganj)",
      "Gumla",
      "Latehar",
      "Palamu",
      "Chatra",
      "Sahibganj",
      "Godda",
      "Pakur",
      "Garhwa",
      "Khunti",
      "Simdega",
      "Koderma",
    ],
  },
  "ROC Shillong": {
    state: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Williamnagar",
      "Nongstoin",
      "Nongpoh",
      "Ampati",
      "Resubelpara",
      "Dadenggre",
      "Mendipathar",
    ],
  },
  "ROC Pondicherry": {
    union_territory: "Pondicherry",
    cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  },
  "ROC Andaman": {
    union_territory: "Andaman & Nicobar",
    cities: [
      "South Andaman District",
      "North and Middle Andaman District",
      "Nicobar District",
    ],
  },
};
