name: Deploy to Server

on:
  push:
    branches:
      - main # Change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ff-apps/admin-frontend
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d --remove-orphans
